/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yvtehjfwuhotkjdlogvz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2dGVoamZ3dWhvdGtqZGxvZ3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1MDQwNDgsImV4cCI6MjA5MTA4MDA0OH0.0gSe_ILBwOVpB4KnA07iKB5Kr7nuvEvn1AETjJDi--M"